<?php
$setting = Mage::helper('galagiftshopsettings');
?>
<link rel="stylesheet" id="emcssvariation" type="text/css" href="<?php echo $this->getSkinUrl('css/theme.css.php').'?ie=1&'.http_build_query($setting->getAllCssConfig(), '', '&amp;'); ?>"></link>

<!--[if lt IE 9]>
<script type="text/javascript">
(function() {
	var el = document.getElementById('emcssvariation');
	el.parentNode.removeChild(el);
})();
</script>
<link rel="stylesheet" id="emcssvariation" type="text/css" href="<?php echo $this->getSkinUrl('css/theme.css.php').'?ie=1&'.http_build_query($setting->getAllCssConfig(), '', '&amp;'); ?>"></link>
<![endif]-->

<?php if ($setting->getTypography_GoogleFonts()): ?>
<?php 
	$fontArray = explode(',',$setting->getTypography_GoogleFonts());
	$fontIncArray = array();
	foreach($fontArray as $font){
		$fontIncArray[] = "'".str_replace(' ','+',$font).":400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic:cyrillic-ext,latin,greek-ext,greek,vietnamese,latin-ext'";
	}
?>
<script type="text/javascript">
  WebFontConfig = {
    google: { families: [<?php echo implode(',',$fontIncArray)?>]}
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
        '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })();
</script>
<?php endif ?>

<style type="text/css">
<?php echo $setting->getTypography_CustomCss(); ?>
</style>

<script type="text/javascript">
//<![CDATA[
var urlSkinsite = '<?php echo $this->getSKinUrl(); ?>';
LightboxOptions = Object.extend({
    fileLoadingImage:        urlSkinsite+'images/loading.gif',     
    fileBottomNavCloseImage: urlSkinsite+'images/closelabel.gif',

    overlayOpacity: 0.8,   // controls transparency of shadow overlay

    animate: true,         // toggles resizing animations
    resizeSpeed: 7,        // controls the speed of the image resizing animations (1=slowest and 10=fastest)

    borderSize: 10,         //if you adjust the padding in the CSS, you will need to update this variable

	// When grouping images this is used to write: Image # of #.
	// Change it for non-english localization
	labelImage: "Image",
	labelOf: "of"
}, window.LightboxOptions || {});
//]]>
</script>
