(function($){var ANIMATION_SPEED='normal';var isMobile=/iPhone|iPod|iPad|Phone|Mobile|Android|hpwos/i.test(navigator.userAgent);var isPhone=/iPhone|iPod|Phone|Android/i.test(navigator.userAgent);function isMobileView(){return $('body').hasClass('adapt-0');}
function mobile(){var skipHashChange=false;function hashchange(){if(!isMobileView())return;if(skipHashChange){skipHashChange=false;return;}
var m;if(location.hash&&(m=location.hash.match(/^#menu\/(.*)$/))){var hash=m[1].split('/');if(hash.length==0)return;var $nav=$('.em_nav').eq(hash.shift()).find('.hnav, .vnav');var $el=$nav;if($el.length>0){$('.mhover',$nav).removeClass('mhover');var left=0;while(hash.length>0){$el=$el.children().eq(hash.shift());if($el.hasClass('menu-item-link')||$el.get(0).tagName=='LI'&&$el.parents('.em-catalog-navigation').length>0){$el.addClass('mhover');left-=$nav.width();}}
$nav.animate({'margin-left':left+'px'},ANIMATION_SPEED);}}
else if(!location.hash){var $nav=$('.em_nav .hnav, .em_nav .vnav');$('.mhover',$nav).removeClass('mhover');$nav.animate({'margin-left':''},ANIMATION_SPEED);}}
hashchange();$(window).hashchange(hashchange)
$(window).bind('emadaptchange',function(){if(isMobileView()){hashchange();}
else{$('.em_nav .hnav, .em_nav .vnav').css('margin-left','').find('.mhover').removeClass('mhover');}});$('.em_nav').each(function(i){var $nav=$('.hnav, .vnav',this);$('.em-catalog-navigation li.parent, .menu-item-link.menu-item-parent',$nav).each(function(){$(this).prepend('<a href="javaScript:void(0);" class="arrow"><span>&gt;</span></a>');});$('a.arrow',$nav).bind(isMobile?'click mouseenter':'click',function(event){if(!isMobileView())return;event.preventDefault();event.stopPropagation();var $li=$(this.parentNode);if($li.hasClass('mhover'))return;if(event.which==0||event.screenX==0&&event.screenY==0)return;$('.mhover',$nav).not($li.parents('.mhover')).removeClass('mhover');$li.addClass('mhover');var idx=[$li.index()];$li.parentsUntil($nav).each(function(){idx.unshift($(this).index());});location='#menu/'+i+'/'+idx.join('/');});});}
function fixMegaMenuOverflow(){function fix($container,$nav){var pad=$nav.offset().left+$nav.outerWidth()-($container.offset().left+$container.outerWidth());var pad2=$container.offset().left+pad-$nav.offset().left;if(pad2<0)pad=pad-pad2;if(pad<0){$container.css('left',pad+'px');}}
$('.em_nav > .hnav > .menu-item-link > .menu-container').parent().mouseover(function(){var $container=$(this).children('.menu-container');if($(this).hasClass('menu-item-depth-0')){var isIE8=$.browser.msie&&+$.browser.version===8;if(isIE8){$container.css('display','block');}
$container.css('left',0);}
var $nav=$(this).parents('.em_nav').first();fix($container,$nav);});$('.em_nav > .hnav > .menu-item-link > .menu-container').parent().mouseout(function(){var $container=$(this).children('.menu-container');var isIE8=$.browser.msie&&+$.browser.version===8;if(isIE8){$container.css('display','none');}
$(this).children('.menu-container').css('left','');});}
function menu(){$('.vnav ul.level0,.vnav > .menu-item-link > .menu-container').parent().mouseover(function(){var $container=$(this).children('.menu-container,ul.level0');var $containerHeight=$container.outerHeight();var $containerTop=$container.offset().top;var $winHeight=$(window).height();var $maxHeight=$containerHeight+$containerTop;if($maxHeight>=$winHeight){$setTop=$(this).parent().offset().top-$(this).offset().top-10;if(($setTop+$containerHeight)<$(this).height()){$setTop=$(this).outerHeight()-$containerHeight;}}else{$setTop=(-1);}
var $grid=$(this).parents('.em_nav').first().parents().first();$container.css('top',$setTop);if($maxHeight<$winHeight){$('.vnav ul.level0,.vnav > .menu-item-link > .menu-container').first().css('top',$setTop-9+'px');}});$('.vnav .menu-item-link > .menu-container,.vnav ul.level0').parent().mouseout(function(){var $container=$(this).children('.menu-container,ul.level0');$container.removeAttr('style');});}
$(document).ready(function(){fixMegaMenuOverflow();mobile();});})(jQuery);